const express = require('express')
const cors=require("cors")
const dBconnect = require('./config/dBconnect')
const userRouter=require("./features/routes/users.routes")
const eventsRouter=require("./features/routes/events.routes")
const bookingRouter=require("./features/routes/bookedEvents.route")
const app = express()
app.use(express.json())
app.use(cors())
app.use(express.urlencoded({extended: true}))
app.get('/', (req, res) => res.send('hello users'))
app.use("/users",userRouter)
app.use("/events",eventsRouter)
app.use("/bookings",bookingRouter)
app.listen(8080, async() => {
    await dBconnect()
    console.log('server started on port http://localhost:8080')
})